//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.MsgSubscribe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MsgSubscribe.IMsgSubscribe")]
    public interface IMsgSubscribe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMsgSubscribe/DoWork", ReplyAction="http://tempuri.org/IMsgSubscribe/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMsgSubscribe/Subscribe", ReplyAction="http://tempuri.org/IMsgSubscribe/SubscribeResponse")]
        void Subscribe();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMsgSubscribeChannel : WcfClient.MsgSubscribe.IMsgSubscribe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsgSubscribeClient : System.ServiceModel.ClientBase<WcfClient.MsgSubscribe.IMsgSubscribe>, WcfClient.MsgSubscribe.IMsgSubscribe {
        
        public MsgSubscribeClient() {
        }
        
        public MsgSubscribeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MsgSubscribeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgSubscribeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgSubscribeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
    }
}
