//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodInfo_MngPlatform.CommServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommServiceReference.ICommonService")]
    public interface ICommonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDataLisList", ReplyAction="http://tempuri.org/ICommonService/GetDataLisListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_List[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_List))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Ris_List[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Ris_List))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_Result[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.CompositeType))]
        CommonServiceLibrary.Lis_List[] GetDataLisList(string sql, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDataRisList", ReplyAction="http://tempuri.org/ICommonService/GetDataRisListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_List[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_List))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Ris_List[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Ris_List))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_Result[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.CompositeType))]
        CommonServiceLibrary.Ris_List[] GetDataRisList(string sql, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDataLisResult", ReplyAction="http://tempuri.org/ICommonService/GetDataLisResultResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_List[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_List))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Ris_List[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Ris_List))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_Result[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.Lis_Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonServiceLibrary.CompositeType))]
        CommonServiceLibrary.Lis_Result[] GetDataLisResult(string sql, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetData", ReplyAction="http://tempuri.org/ICommonService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ICommonService/GetDataUsingDataContractResponse")]
        CommonServiceLibrary.CompositeType GetDataUsingDataContract(CommonServiceLibrary.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonServiceChannel : BloodInfo_MngPlatform.CommServiceReference.ICommonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonServiceClient : System.ServiceModel.ClientBase<BloodInfo_MngPlatform.CommServiceReference.ICommonService>, BloodInfo_MngPlatform.CommServiceReference.ICommonService {
        
        public CommonServiceClient() {
        }
        
        public CommonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommonServiceLibrary.Lis_List[] GetDataLisList(string sql, object[] args) {
            return base.Channel.GetDataLisList(sql, args);
        }
        
        public CommonServiceLibrary.Ris_List[] GetDataRisList(string sql, object[] args) {
            return base.Channel.GetDataRisList(sql, args);
        }
        
        public CommonServiceLibrary.Lis_Result[] GetDataLisResult(string sql, object[] args) {
            return base.Channel.GetDataLisResult(sql, args);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public CommonServiceLibrary.CompositeType GetDataUsingDataContract(CommonServiceLibrary.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
